- builtin
- name: "@typescript-eslint/eslint-plugin"
  prefix: "@typescript-eslint"
- name: "eslint-plugin-vue"
  prefix: "vue"
- name: "eslint-plugin-sonarjs"
  prefix: "sonarjs"
- name: "@shopify/eslint-plugin"
  prefix: "@shopify"
- name: "eslint-plugin-react"
  prefix: "react"
- name: "eslint-plugin-react-perf"
  prefix: "react-perf"
- name: "eslint-plugin-react-hooks"
  prefix: "react-hooks"
- name: "eslint-plugin-unicorn"
  prefix: "unicorn"
- name: "eslint-plugin-prettier"
  prefix: "prettier"
- name: "eslint-plugin-jest"
  prefix: "jest"
- name: "eslint-plugin-testing-library"
  prefix: "testing-library"
- name: "eslint-plugin-jest-dom"
  prefix: "jest-dom"
