- builtin
- name: "@typescript-eslint/eslint-plugin"
  prefix: "@typescript-eslint"
- name: eslint-plugin-vue
  prefix: vue
- name: eslint-plugin-sonarjs
  prefix: sonarjs
- name: "@shopify/eslint-plugin"
  prefix: "@shopify"
- name: eslint-plugin-react
  prefix: react
- name: eslint-plugin-react-perf
  prefix: react-perf
- name: eslint-plugin-react-hooks
  prefix: react-hooks
- name: eslint-plugin-unicorn
  prefix: unicorn
- name: eslint-plugin-prettier
  prefix: prettier
- name: eslint-plugin-jest
  prefix: jest
- name: eslint-plugin-testing-library
  prefix: testing-library
- name: eslint-plugin-jest-dom
  prefix: jest-dom
- name: eslint-plugin-react-refresh
  prefix: react-refresh
- name: eslint-plugin-react-native
  prefix: react-native
- name: eslint-plugin-jsx-a11y
  prefix: jsx-a11y
- name: eslint-plugin-react-native-a11y
  prefix: react-native-a11y
- name: eslint-plugin-functional
  prefix: functional
- name: eslint-plugin-node
  prefix: node
- name: eslint-plugin-security
  prefix: security
- name: "@graphql-eslint/eslint-plugin" # FIXME
  prefix: "graphql"
- name: "@next/eslint-plugin-next"
  prefix: "@next"
- name: eslint-plugin-collation
  prefix: collation
- name: eslint-plugin-react-hooks-addons
  prefix: react-hooks-addons
- name: eslint-plugin-oxlint
  prefix: oxc
