match: jest
plugins:
  - eslint-plugin-jest
  - eslint-plugin-jest-dom
  - eslint-plugin-testing-library
overrides:
  - files: ["*.test.*", "*.spec.*"]
    rules:
      # jest-dom
      jest-dom/prefer-checked: error
      jest-dom/prefer-empty: error
      jest-dom/prefer-enabled-disabled: error
      jest-dom/prefer-focus: error
      jest-dom/prefer-in-document: error
      jest-dom/prefer-required: error
      jest-dom/prefer-to-have-attribute: error
      jest-dom/prefer-to-have-class: error
      jest-dom/prefer-to-have-style: error
      jest-dom/prefer-to-have-text-content: error
      jest-dom/prefer-to-have-value: error
      # jest
      jest/consistent-test-it: error
      jest/expect-expect: warn
      jest/max-expects: off
      jest/max-nested-describe: warn
      jest/no-alias-methods: error
      jest/no-commented-out-tests: warn
      jest/no-conditional-expect: error
      jest/no-conditional-in-test: error
      jest/no-deprecated-functions: off # auto detection broken
      jest/no-disabled-tests: warn
      jest/no-done-callback: error
      jest/no-duplicate-hooks: error
      jest/no-export: error
      jest/no-focused-tests: warn
      jest/no-hooks: off
      jest/no-identical-title: error
      jest/no-if: off
      jest/no-interpolation-in-snapshots: error
      jest/no-jasmine-globals: off
      jest/no-large-snapshots: warn
      jest/no-mocks-import: error
      jest/no-restricted-jest-methods: off
      jest/no-restricted-matchers: off
      jest/no-standalone-expect: error
      jest/no-test-prefixes: error
      jest/no-test-return-statement: error
      jest/no-untyped-mock-factory: off
      jest/prefer-called-with: warn
      jest/prefer-comparison-matcher: error
      jest/prefer-each: error
      jest/prefer-equality-matcher: error
      jest/prefer-expect-assertions: off
      jest/prefer-expect-resolves: error
      jest/prefer-hooks-in-order: error
      jest/prefer-hooks-on-top: error
      jest/prefer-lowercase-title: off
      jest/prefer-mock-promise-shorthand: off # breaks typings
      jest/prefer-snapshot-hint: off
      jest/prefer-spy-on: error
      jest/prefer-strict-equal: off
      jest/prefer-to-be: warn
      jest/prefer-to-contain: error
      jest/prefer-to-have-length: error
      jest/prefer-todo: error
      jest/require-hook: error
      jest/require-to-throw-message: warn
      jest/require-top-level-describe: error
      jest/unbound-method: error
      jest/valid-describe-callback: error
      jest/valid-expect-in-promise: error
      jest/valid-expect: error
      jest/valid-title: error
      # testing-library
      testing-library/await-async-query: error
      testing-library/await-async-utils: error
      testing-library/await-fire-event: off
      testing-library/consistent-data-testid: off
      testing-library/no-await-sync-events: off
      testing-library/no-await-sync-query: error
      testing-library/no-container: error
      testing-library/no-debugging-utils: warn
      testing-library/no-dom-import: error
      testing-library/no-global-regexp-flag-in-query: error
      testing-library/no-manual-cleanup: error
      testing-library/no-node-access: error
      testing-library/no-promise-in-fire-event: error
      testing-library/no-render-in-setup: error
      testing-library/no-unnecessary-act: error
      testing-library/no-wait-for-empty-callback: error
      testing-library/no-wait-for-multiple-assertions: error
      testing-library/no-wait-for-side-effects: error
      testing-library/no-wait-for-snapshot: error
      testing-library/prefer-explicit-assert: error
      testing-library/prefer-find-by: error
      testing-library/prefer-presence-queries: error
      testing-library/prefer-query-by-disappearance: error
      testing-library/prefer-query-matchers: off
      testing-library/prefer-screen-queries: error
      testing-library/prefer-user-event: error
      testing-library/prefer-wait-for: error
      testing-library/render-result-naming-convention: error
