# explore: true
match: node
plugins:
  - eslint-plugin-node
rules:
  # errors
  node/callback-return: error
  node/no-exports-assign: error
  node/no-extraneous-import: error
  node/no-extraneous-require: error
  node/no-missing-import: off
  node/no-missing-require: off
  node/no-unpublished-bin: off
  node/no-unpublished-import: off
  node/no-unpublished-require: off
  node/no-unsupported-features/es-builtins: error
  node/no-unsupported-features/es-syntax: off
  # - error
  # - ignores: [modules]
  node/no-unsupported-features/node-builtins: error
  node/process-exit-as-throw: error
  node/shebang: off
  # best practices
  node/no-deprecated-api: error
  # style
  node/exports-style: error
  node/file-extension-in-import: off
  node/global-require: warn
  node/handle-callback-err: error
  node/no-callback-literal: error
  node/no-mixed-requires: off
  node/no-new-require: error
  node/no-path-concat: error
  node/no-process-env: off
  node/no-process-exit: warn
  node/no-sync: off
  # - error
  # - { allowAtRootLevel: true }
  node/prefer-global/buffer: error
  node/prefer-global/console: error
  node/prefer-global/process: error
  node/prefer-global/text-decoder: error
  node/prefer-global/text-encoder: error
  node/prefer-global/url-search-params: error
  node/prefer-global/url: error
  node/prefer-promises/dns: error
  node/prefer-promises/fs: error
  # deprecated
  node/no-hide-core-modules: off
  node/no-unsupported-features: off
  # custom
  node/no-restricted-import:
    - off
    - name: lodash/*
      message: Please use X instead.
    - name:
        - for/*
        - "!example/x"
  node/no-restricted-require: off
