match: react-native
plugins:
  - eslint-plugin-react-native
  - eslint-plugin-react-native-a11y
env:
  react-native/react-native: true
rules:
  # react-native
  react-native/no-color-literals: warn
  react-native/no-inline-styles: warn
  react-native/no-raw-text: error
  react-native/no-single-element-style-arrays: warn
  react-native/no-unused-styles: error
  react-native/sort-styles: off
  react-native/split-platform-components: error
  # react-native-a11y
  react-native-a11y/has-accessibility-hint: warn
  react-native-a11y/has-accessibility-props: off
  react-native-a11y/has-valid-accessibility-actions: error
  react-native-a11y/has-valid-accessibility-component-type: error
  react-native-a11y/has-valid-accessibility-descriptors: error
  react-native-a11y/has-valid-accessibility-ignores-invert-colors: error
  react-native-a11y/has-valid-accessibility-live-region: error
  react-native-a11y/has-valid-accessibility-role: error
  react-native-a11y/has-valid-accessibility-state: error
  react-native-a11y/has-valid-accessibility-states: error
  react-native-a11y/has-valid-accessibility-traits: error
  react-native-a11y/has-valid-accessibility-value: error
  react-native-a11y/has-valid-important-for-accessibility: error
  react-native-a11y/no-nested-touchables: off
