# explore: true
match: react
plugins:
  - eslint-plugin-react
  - eslint-plugin-react-hooks
  - eslint-plugin-react-perf
  - eslint-plugin-react-refresh
settings:
  react:
    version: detect
rules:
  # react
  react/boolean-prop-naming:
    - warn
    - validateNested: true
      rule: "^(is|has|was|will|did|can|enable|disable|no|ignore|force|hide|with|disabled|allow|default|initial)[A-Z]([A-Za-z0-9]?)+|disabled"
  react/button-has-type: off
  react/default-props-match-prop-types: error
  react/destructuring-assignment: off
  react/display-name: off
  react/forbid-component-props: off
  react/forbid-dom-props: off
  react/forbid-elements: off
  react/forbid-foreign-prop-types: error
  react/forbid-prop-types: off
  react/function-component-definition: off
  react/hook-use-state: error
  react/iframe-missing-sandbox: error
  react/jsx-boolean-value: off
  react/jsx-child-element-spacing: off
  react/jsx-closing-bracket-location: off
  react/jsx-closing-tag-location: off
  react/jsx-curly-brace-presence: error
  react/jsx-curly-newline: off
  react/jsx-curly-spacing: off
  react/jsx-equals-spacing: off
  react/jsx-filename-extension: off
  react/jsx-first-prop-new-line: off
  react/jsx-fragments: off
  react/jsx-handler-names: off
  react/jsx-indent-props: off
  react/jsx-indent: off
  react/jsx-key: error
  react/jsx-max-depth: off
  react/jsx-max-props-per-line: off
  react/jsx-newline: off
  react/jsx-no-bind: off
  react/jsx-no-comment-textnodes: error
  react/jsx-no-constructed-context-values: error
  react/jsx-no-duplicate-props: error
  react/jsx-no-leaked-render: off
  react/jsx-no-literals: off
  react/jsx-no-script-url: error
  react/jsx-no-target-blank: off
  react/jsx-no-undef: error
  react/jsx-no-useless-fragment: off
  react/jsx-one-expression-per-line: off
  react/jsx-pascal-case: error
  react/jsx-props-no-multi-spaces: off
  react/jsx-props-no-spreading: off
  react/sort-prop-types:
    - error
    - callbacksLast: true
      noSortAlphabetically: true
      sortShapeProp: true
  react/jsx-sort-props:
    - error
    - callbacksLast: true
      multiline: ignore
      noSortAlphabetically: true
      reservedFirst: true
      shorthandFirst: false
      shorthandLast: true
  react/jsx-space-before-closing: off
  react/jsx-tag-spacing: off
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-wrap-multilines: off
  react/no-access-state-in-setstate: error
  react/no-adjacent-inline-elements: error
  react/no-array-index-key: error
  react/no-arrow-function-lifecycle: error
  react/no-children-prop: error
  react/no-danger-with-children: error
  react/no-danger: error
  react/no-deprecated: error
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-direct-mutation-state: error
  react/no-find-dom-node: error
  react/no-invalid-html-attribute: error
  react/no-is-mounted: error
  react/no-multi-comp: off
  react/no-namespace: error
  react/no-object-type-as-default-prop: error
  react/no-redundant-should-component-update: error
  react/no-render-return-value: error
  react/no-set-state: off
  react/no-string-refs: error
  react/no-this-in-sfc: error
  react/no-typos: error
  react/no-unescaped-entities: error
  react/no-unknown-property: error
  react/no-unsafe: error
  react/no-unstable-nested-components: error
  react/no-unused-class-component-methods: error
  react/no-unused-prop-types: error
  react/no-unused-state: error
  react/no-will-update-set-state: error
  react/prefer-es6-class: error
  react/prefer-exact-props: off
  react/prefer-read-only-props: off
  react/prefer-stateless-function: error
  react/prop-types: off
  react/react-in-jsx-scope: off
  react/require-default-props: off
  react/require-optimization: off
  react/require-render-return: error
  react/self-closing-comp: error
  react/sort-comp: off
  react/state-in-constructor: off
  react/static-property-placement: off
  react/style-prop-object: error
  react/void-dom-elements-no-children: error
  react/sort-default-props:
    - error
    - ignoreCase: false
  react/jsx-sort-default-props: off # deprecated
  # react/checked-requires-onchange-or-readonly: error
  # react-hooks
  react-hooks/exhaustive-deps: warn
  react-hooks/rules-of-hooks: error
  # react-perf
  react-perf/jsx-no-jsx-as-prop: off
  react-perf/jsx-no-new-array-as-prop: off
  react-perf/jsx-no-new-function-as-prop: off
  react-perf/jsx-no-new-object-as-prop: off
  # react-refresh
  react-refresh/only-export-components: off
