# explore: true
plugins:
  - eslint-plugin-unicorn
rules:
  # sanity
  unicorn/better-regex: error
  unicorn/catch-error-name: error
  unicorn/consistent-destructuring: error
  unicorn/consistent-function-scoping: off
  unicorn/custom-error-definition: error
  unicorn/error-message: error
  unicorn/escape-case: off
  unicorn/expiring-todo-comments: off
  unicorn/explicit-length-check: error
  unicorn/filename-case: off
  unicorn/import-index: off
  unicorn/import-style: off
  unicorn/new-for-builtins: error
  unicorn/no-abusive-eslint-disable: off
  unicorn/no-array-callback-reference: off
  unicorn/no-array-for-each: error
  unicorn/no-array-method-this-argument: error
  unicorn/no-array-push-push: off
  unicorn/no-array-reduce: off
  unicorn/no-console-spaces: error
  unicorn/no-document-cookie: warn
  unicorn/no-for-loop: error
  unicorn/no-hex-escape: error
  unicorn/no-instanceof-array: error
  unicorn/no-invalid-remove-event-listener: error
  unicorn/no-lonely-if: error
  unicorn/no-nested-ternary: error
  unicorn/no-new-array: error
  unicorn/no-new-buffer: error
  unicorn/no-null: off
  unicorn/no-object-as-default-parameter: off
  unicorn/no-process-exit: off
  unicorn/no-static-only-class: error
  unicorn/no-this-assignment: off
  unicorn/no-unreadable-array-destructuring: error
  unicorn/no-unused-properties: error
  unicorn/no-useless-fallback-in-spread: error
  unicorn/no-useless-length-check: error
  unicorn/no-useless-spread: error
  unicorn/no-useless-undefined: off
  unicorn/no-zero-fractions: error
  unicorn/number-literal-case: error
  unicorn/numeric-separators-style: error
  unicorn/prefer-add-event-listener: error
  unicorn/prefer-array-find: error
  unicorn/prefer-array-flat-map: error
  unicorn/prefer-array-flat: error
  unicorn/prefer-array-index-of: error
  unicorn/prefer-array-some: error
  unicorn/prefer-at: off
  unicorn/prefer-blob-reading-methods: error
  unicorn/prefer-date-now: error
  unicorn/prefer-default-parameters: error
  unicorn/prefer-dom-node-append: error
  unicorn/prefer-dom-node-dataset: error
  unicorn/prefer-dom-node-remove: off
  unicorn/prefer-dom-node-text-content: error
  unicorn/prefer-includes: error
  unicorn/prefer-keyboard-event-key: error
  unicorn/prefer-math-trunc: error
  unicorn/prefer-modern-dom-apis: error
  unicorn/prefer-module: off
  unicorn/prefer-negative-index: error
  unicorn/prefer-node-protocol: off
  unicorn/prefer-number-properties: error
  unicorn/prefer-object-from-entries: off
  unicorn/prefer-object-has-own: off # deprecated
  unicorn/prefer-optional-catch-binding: error
  unicorn/prefer-prototype-methods: error
  unicorn/prefer-query-selector: off
  unicorn/prefer-reflect-apply: error
  unicorn/prefer-regexp-test: off
  unicorn/prefer-set-has: error
  unicorn/prefer-spread: off
  unicorn/prefer-string-replace-all: off
  unicorn/prefer-string-slice: error
  unicorn/prefer-string-starts-ends-with: error
  unicorn/prefer-string-trim-start-end: error
  unicorn/prefer-switch: off
  unicorn/prefer-ternary: off
  unicorn/prefer-top-level-await: off
  unicorn/prefer-type-error: error
  unicorn/prevent-abbreviations:
    - off
    - checkFilenames: false
      allowList:
        params: true
        devtools: true
        env: true
        props: true
        acc: true
        curr: true
        args: true
        str: true
        isDev: true
        ref: true
        arr: true
        dev: true
        IProps: true
        TProps: true
  unicorn/require-array-join-separator: error
  unicorn/require-number-to-fixed-digits-argument: error
  unicorn/require-post-message-target-origin: off
  unicorn/throw-new-error: error
  unicorn/text-encoding-identifier-case: error
  unicorn/relative-url-style: ["error", "always"]
  unicorn/prefer-native-coercion-functions: error
  unicorn/prefer-modern-math-apis: error
  unicorn/prefer-export-from: ["error", { "ignoreUsedVariables": true }]
  unicorn/no-useless-switch-case: error
  unicorn/no-useless-promise-resolve-reject: error
  unicorn/no-unreadable-iife: error
  unicorn/no-thenable: error
  unicorn/no-await-expression-member: error
  unicorn/prefer-code-point: error
  unicorn/no-empty-file: off
  # style
  unicorn/empty-brace-spaces: off
  unicorn/template-indent: off
  # deprecated
  unicorn/no-array-instanceof: off
  unicorn/no-fn-reference-in-iterator: off
  unicorn/no-reduce: off
  unicorn/prefer-dataset: off
  unicorn/prefer-event-key: off
  unicorn/prefer-exponentiation-operator: off
  unicorn/prefer-flat-map: off
  unicorn/prefer-node-append: off
  unicorn/prefer-node-remove: off
  unicorn/prefer-replace-all: off
  unicorn/prefer-starts-ends-with: off
  unicorn/prefer-text-content: off
  unicorn/prefer-trim-start-end: off
  unicorn/regex-shorthand: off
  unicorn/prefer-json-parse-buffer: off
  # custom
  unicorn/string-content: off
  unicorn/no-keyword-prefix: off
  # inbox
  "unicorn/no-unnecessary-await": error
  "unicorn/prefer-event-target": error
  "unicorn/prefer-logical-operator-over-ternary": error
  "unicorn/switch-case-braces": error
  unicorn/prefer-set-size: error
  unicorn/no-typeof-undefined: error
  unicorn/no-negated-condition: off
  unicorn/no-unnecessary-polyfills: error
