match: vue
explore: true
parser: "vue-eslint-parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  extraFileExtensions: [".vue"]
plugins:
  - eslint-plugin-vue
extends:
  - plugin:vue/vue3-recommended
rules:
  # base
  vue/require-explicit-emits: off
  # style
  vue/func-call-spacing: off
  vue/html-comment-content-spacing: off
  vue/html-comment-indent: off
  vue/key-spacing: off
  vue/keyword-spacing: off
  vue/no-irregular-whitespace: off
  vue/object-curly-newline: off
  vue/object-curly-spacing: off
  vue/object-property-newline: off
  vue/operator-linebreak: off
  vue/padding-line-between-blocks: off
  vue/script-indent: off
  vue/sort-keys: off
  vue/space-in-parens: off
  vue/space-infix-ops: off
  vue/space-unary-ops: off
  vue/template-curly-spacing: off
  vue/array-bracket-newline: off
  # other
  vue/component-options-name-casing: error
  vue/define-macros-order: error
  vue/first-attribute-linebreak: error
  vue/match-component-import-name: error
  vue/max-lines-per-block: off
  vue/no-child-content: error
  vue/no-computed-properties-in-data: error
  vue/no-console: error
  vue/no-deprecated-router-link-tag-prop: error
  vue/no-expose-after-await: error
  vue/no-loss-of-precision: error
  vue/no-reserved-props: error
  vue/no-root-v-if: error
  vue/no-undef-components: error
  vue/no-undef-properties: off
  vue/no-v-text-v-html-on-component: error
  vue/object-shorthand: error
  vue/prefer-import-from-vue: error
  vue/prefer-prop-type-boolean-first: error
  vue/prefer-separate-static-class: error
  vue/prefer-true-attribute-shorthand: error
  vue/quote-props: [error, as-needed]
  # custom
  vue/array-element-newline: off
  vue/multiline-ternary: error
  vue/no-required-prop-with-default: error
  vue/no-restricted-block: off
  vue/no-restricted-call-after-await: off
  vue/no-restricted-class: off
  vue/no-restricted-component-options: off
  vue/no-restricted-custom-event: off
  vue/no-restricted-html-elements: off
  vue/no-restricted-props: off
  vue/no-restricted-static-attribute: off
  vue/no-restricted-syntax: off
  vue/no-restricted-v-bind: off
  vue/padding-line-between-tags: off
  vue/padding-lines-in-component-definition: off
  vue/require-prop-comment: off
  vue/valid-attribute-name: error
  vue/valid-model-definition: error
  vue/no-restricted-component-names: off
  # new
  vue/array-bracket-spacing: off
  vue/arrow-spacing: off
  vue/attribute-hyphenation: error
  vue/attributes-order: error
  vue/block-lang: error
  vue/block-spacing: off
  vue/block-tag-newline: off
  vue/brace-style: off
  vue/camelcase: error
  vue/comma-dangle: off
  vue/comma-spacing: off
  vue/comma-style: off
  vue/comment-directive: off
  vue/component-api-style: off
  vue/component-definition-name-casing: error
  vue/component-name-in-template-casing: error
  vue/component-tags-order: error
  vue/custom-event-name-casing: error
  vue/define-emits-declaration: error
  vue/define-props-declaration: error
  vue/dot-location: error
  vue/dot-notation: error
  vue/eqeqeq: error
  vue/html-button-has-type: error
  vue/html-closing-bracket-newline: off
  vue/html-closing-bracket-spacing: off
  vue/html-end-tags: off
  vue/html-indent: off
  vue/html-quotes: off
  vue/html-self-closing: off
  vue/jsx-uses-vars: error
  vue/match-component-file-name: error
  vue/max-attributes-per-line: off
  vue/max-len: off
  vue/multi-word-component-names: off
  vue/mustache-interpolation-spacing: off
  vue/new-line-between-multi-line-property: off
  vue/next-tick-style: off
  vue/no-arrow-functions-in-watch: off
  vue/no-async-in-computed-properties: error
  vue/no-bare-strings-in-template: error
  vue/no-boolean-default: error
  vue/no-constant-condition: error
  vue/no-custom-modifiers-on-v-model: error
  vue/no-deprecated-data-object-declaration: error
  vue/no-deprecated-destroyed-lifecycle: error
  vue/no-deprecated-dollar-listeners-api: error
  vue/no-deprecated-events-api: error
  vue/no-deprecated-filter: error
  vue/no-deprecated-functional-template: error
  vue/no-deprecated-html-element-is: error
  vue/no-deprecated-inline-template: error
  vue/no-deprecated-props-default-this: error
  vue/no-deprecated-scope-attribute: error
  vue/no-deprecated-slot-scope-attribute: error
  vue/no-deprecated-v-bind-sync: error
  vue/no-deprecated-v-is: error
  vue/no-deprecated-v-on-number-modifiers: error
  vue/no-deprecated-vue-config-keycodes: error
  vue/no-dupe-keys: error
  vue/no-dupe-v-else-if: error
  vue/no-duplicate-attr-inheritance: error
  vue/no-duplicate-attributes: error
  vue/no-empty-component-block: error
  vue/no-empty-pattern: error
  vue/no-export-in-script-setup: error
  vue/no-extra-parens: off
  vue/no-invalid-model-keys: error
  vue/no-lifecycle-after-await: error
  vue/no-lone-template: error
  vue/no-multiple-objects-in-class: error
  vue/no-multiple-slot-args: error
  vue/no-multiple-template-root: error
  vue/no-mutating-props: error
  vue/no-parsing-error: error
  vue/no-potential-component-option-typo: error
  vue/no-ref-as-operand: error
  vue/no-ref-object-destructure: error
  vue/no-reserved-component-names: off
  vue/no-reserved-keys: off
  vue/no-setup-props-destructure: error
  vue/no-shared-component-data: error
  vue/no-side-effects-in-computed-properties: error
  vue/no-spaces-around-equal-signs-in-attribute: off
  vue/no-sparse-arrays: error
  vue/no-static-inline-styles: error
  vue/no-template-key: error
  vue/no-template-shadow: error
  vue/no-template-target-blank: error
  vue/no-textarea-mustache: error
  vue/no-this-in-before-route-enter: error
  vue/no-unsupported-features: error
  vue/no-unused-components: error
  vue/no-unused-properties: error
  vue/no-unused-refs: error
  vue/no-unused-vars: error
  vue/no-use-computed-property-like-method: error
  vue/no-use-v-if-with-v-for: error
  vue/no-useless-concat: error
  vue/no-useless-mustaches: error
  vue/no-useless-template-attributes: error
  vue/no-useless-v-bind: error
  vue/no-v-for-template-key-on-child: error
  vue/no-v-for-template-key: error
  vue/no-v-html: error
  vue/no-v-model-argument: error
  vue/no-v-text: error
  vue/no-watch-after-await: error
  vue/one-component-per-file: error
  vue/order-in-components: off
  vue/prefer-define-options: off
  vue/prefer-template: off
  vue/prop-name-casing: off
  vue/require-component-is: off
  vue/require-default-prop: off
  vue/require-direct-export: off
  vue/require-emit-validator: off
  vue/require-expose: off
  vue/require-macro-variable-name: off
  vue/require-name-property: off
  vue/require-prop-type-constructor: off
  vue/require-prop-types: off
  vue/require-render-return: off
  vue/require-slots-as-functions: off
  vue/require-toggle-inside-transition: off
  vue/require-typed-ref: off
  vue/require-v-for-key: off
  vue/require-valid-default-prop: off
  vue/return-in-computed-property: off
  vue/return-in-emits-validator: off
  vue/script-setup-uses-vars: off
  vue/singleline-html-element-content-newline: off
  vue/static-class-names-order: off
  vue/this-in-template: off
  vue/use-v-on-exact: off
  vue/v-bind-style: off
  vue/v-for-delimiter-style: off
  vue/v-on-event-hyphenation: off
  vue/v-on-function-call: off
  vue/v-on-handler-style: off
  vue/v-on-style: off
  vue/v-slot-style: off
  vue/valid-define-emits: error
  vue/valid-define-options: error
  vue/valid-define-props: error
  vue/valid-next-tick: error
  vue/valid-template-root: error
  vue/valid-v-bind-sync: error
  vue/valid-v-bind: error
  vue/valid-v-cloak: error
  vue/valid-v-else-if: error
  vue/valid-v-else: error
  vue/valid-v-for: error
  vue/valid-v-html: error
  vue/valid-v-if: error
  vue/valid-v-is: error
  vue/valid-v-memo: error
  vue/valid-v-model: error
  vue/valid-v-on: error
  vue/valid-v-once: error
  vue/valid-v-pre: error
  vue/valid-v-show: error
  vue/valid-v-slot: error
  vue/valid-v-text: error
  vue/multiline-html-element-content-newline: off
  vue/no-deprecated-slot-attribute: error
  vue/no-deprecated-v-on-native-modifier: error
  vue/no-multi-spaces: off
  vue/html-comment-content-newline: off
  vue/no-deprecated-dollar-scopedslots-api: off
