match: vue2
explore: true
plugins:
  - eslint-plugin-vue
extends:
  - plugin:vue/recommended
rules:
  # extension
  vue/attribute-hyphenation: warn
  vue/attributes-order: warn
  vue/comment-directive: error
  vue/component-definition-name-casing: warn
  vue/component-tags-order: warn
  vue/html-closing-bracket-newline: warn
  vue/html-closing-bracket-spacing: warn
  vue/html-end-tags: warn
  vue/html-indent: off
  vue/html-quotes: off
  vue/html-self-closing: warn
  vue/jsx-uses-vars: error
  vue/max-attributes-per-line: off
  vue/multi-word-component-names: off
  vue/multiline-html-element-content-newline: warn
  vue/mustache-interpolation-spacing: warn
  vue/no-arrow-functions-in-watch: error
  vue/no-async-in-computed-properties: error
  vue/no-custom-modifiers-on-v-model: error
  vue/no-dupe-keys: error
  vue/no-dupe-v-else-if: error
  vue/no-duplicate-attributes: error
  vue/no-lone-template: warn
  vue/no-multi-spaces: warn
  vue/no-multiple-slot-args: warn
  vue/no-multiple-template-root: error
  vue/no-mutating-props: error
  vue/no-parsing-error: error
  vue/no-reserved-keys: error
  vue/no-shared-component-data: error
  vue/no-side-effects-in-computed-properties: error
  vue/no-spaces-around-equal-signs-in-attribute: warn
  vue/no-template-key: error
  vue/no-template-shadow: warn
  vue/no-textarea-mustache: error
  vue/no-unused-components: error
  vue/no-unused-vars: error
  vue/no-use-v-if-with-v-for: error
  vue/no-v-for-template-key: error
  vue/no-v-html: warn
  vue/no-v-model-argument: error
  vue/one-component-per-file: warn
  vue/order-in-components: warn
  vue/prop-name-casing: warn
  vue/require-component-is: error
  vue/require-default-prop: warn
  vue/require-prop-type-constructor: error
  vue/require-prop-types: warn
  vue/require-render-return: error
  vue/require-v-for-key: error
  vue/require-valid-default-prop: error
  vue/return-in-computed-property: error
  vue/script-setup-uses-vars: error
  vue/singleline-html-element-content-newline: warn
  vue/this-in-template: warn
  vue/use-v-on-exact: error
  vue/v-bind-style: warn
  vue/v-on-style: warn
  vue/v-slot-style: warn
  vue/valid-template-root: error
  vue/valid-v-bind-sync: error
  vue/valid-v-bind: error
  vue/valid-v-cloak: error
  vue/valid-v-else-if: error
  vue/valid-v-else: error
  vue/valid-v-for: error
  vue/valid-v-html: error
  vue/valid-v-if: error
  vue/valid-v-model: error
  vue/valid-v-on: error
  vue/valid-v-once: error
  vue/valid-v-pre: error
  vue/valid-v-show: error
  vue/valid-v-slot: error
  vue/valid-v-text: error
  # sanity
  # vue/experimental-script-setup-vars: off
  # vue/name-property-casing: off
  vue/array-bracket-newline: error
  vue/array-bracket-spacing: error
  vue/arrow-spacing: error
  vue/block-lang: off
  vue/block-spacing: off
  vue/block-tag-newline: off
  vue/brace-style: off
  vue/camelcase: off
  vue/comma-dangle: off
  vue/comma-spacing: off
  vue/comma-style: off
  vue/component-api-style: off
  vue/component-name-in-template-casing: error
  vue/custom-event-name-casing: error
  vue/dot-location: off
  vue/dot-notation: error
  vue/eqeqeq: error
  vue/html-button-has-type: off
  vue/match-component-file-name: error
  vue/max-len: off
  vue/new-line-between-multi-line-property: off
  vue/next-tick-style: error
  vue/no-bare-strings-in-template: off
  vue/no-boolean-default: error
  vue/no-constant-condition: error
  vue/no-deprecated-v-is: error
  vue/no-duplicate-attr-inheritance: error
  vue/no-empty-component-block: off
  vue/no-empty-pattern: error
  vue/no-export-in-script-setup: error
  vue/no-extra-parens: off # error
  vue/no-invalid-model-keys: error
  vue/no-multiple-objects-in-class: error
  vue/no-potential-component-option-typo: error
  vue/no-reserved-component-names: error
  vue/no-sparse-arrays: error
  vue/no-static-inline-styles: error
  vue/no-template-target-blank: warn
  vue/no-this-in-before-route-enter: error
  vue/no-unsupported-features: off
  vue/no-unused-properties: error
  vue/no-unused-refs: error
  vue/no-use-computed-property-like-method: error
  vue/no-useless-concat: error
  vue/no-useless-mustaches: error
  vue/no-useless-template-attributes: error
  vue/no-useless-v-bind: error
  vue/no-v-text: error
  vue/prefer-template: error
  vue/require-direct-export: error
  vue/require-emit-validator: error
  vue/require-expose: off
  vue/require-name-property: error
  vue/static-class-names-order: error
  vue/v-for-delimiter-style: error
  vue/v-on-event-hyphenation: [error, always]
  vue/v-on-function-call: [error, never]
  vue/valid-define-emits: error
  vue/valid-define-props: error
  vue/valid-next-tick: error
  vue/valid-v-memo: error
