match: vue3
explore: true
plugins:
  - eslint-plugin-vue
extends:
  - plugin:vue/vue3-recommended
rules:
  # extension
  vue/attribute-hyphenation: warn
  vue/attributes-order: warn
  vue/component-definition-name-casing: warn
  vue/component-tags-order: warn
  vue/define-emits-declaration: off
  vue/define-props-declaration: off
  vue/html-closing-bracket-newline: warn
  vue/html-closing-bracket-spacing: warn
  vue/html-end-tags: warn
  vue/html-indent: off
  vue/html-quotes: off
  vue/html-self-closing: off
  vue/max-attributes-per-line: off
  vue/multi-word-component-names: off
  vue/multiline-html-element-content-newline: warn
  vue/mustache-interpolation-spacing: warn
  vue/no-arrow-functions-in-watch: error
  vue/no-async-in-computed-properties: error
  vue/no-deprecated-data-object-declaration: error
  vue/no-deprecated-destroyed-lifecycle: off
  vue/no-deprecated-dollar-listeners-api: error
  vue/no-deprecated-dollar-scopedslots-api: error
  vue/no-deprecated-events-api: error
  vue/no-deprecated-filter: error
  vue/no-deprecated-functional-template: error
  vue/no-deprecated-html-element-is: error
  vue/no-deprecated-inline-template: error
  vue/no-deprecated-props-default-this: error
  vue/no-deprecated-scope-attribute: error
  vue/no-deprecated-slot-attribute: error
  vue/no-deprecated-slot-scope-attribute: error
  vue/no-deprecated-v-bind-sync: error
  vue/no-deprecated-v-on-native-modifier: error
  vue/no-deprecated-v-on-number-modifiers: error
  vue/no-deprecated-vue-config-keycodes: error
  vue/no-dupe-keys: error
  vue/no-dupe-v-else-if: error
  vue/no-duplicate-attributes: error
  vue/no-lifecycle-after-await: error
  vue/no-lone-template: warn
  vue/no-multi-spaces: warn
  vue/no-multiple-slot-args: warn
  vue/no-mutating-props: error
  vue/no-parsing-error: error
  vue/no-ref-as-operand: error
  vue/no-ref-object-destructure: error
  vue/no-reserved-keys: error
  vue/no-setup-props-destructure: error
  vue/no-shared-component-data: error
  vue/no-side-effects-in-computed-properties: error
  vue/no-spaces-around-equal-signs-in-attribute: warn
  vue/no-template-key: error
  vue/no-template-shadow: warn
  vue/no-textarea-mustache: error
  vue/no-unused-components: error
  vue/no-unused-vars: error
  vue/no-use-v-if-with-v-for: error
  vue/no-v-for-template-key-on-child: error
  vue/no-v-html: warn
  vue/no-watch-after-await: error
  vue/one-component-per-file: warn
  vue/order-in-components: warn
  vue/prefer-define-options: error
  vue/prop-name-casing: warn
  vue/require-component-is: error
  vue/require-default-prop: warn
  vue/require-macro-variable-name: error
  vue/require-prop-type-constructor: error
  vue/require-prop-types: warn
  vue/require-render-return: error
  vue/require-slots-as-functions: error
  vue/require-toggle-inside-transition: error
  vue/require-typed-ref: error
  vue/require-v-for-key: error
  vue/require-valid-default-prop: error
  vue/return-in-computed-property: error
  vue/return-in-emits-validator: error
  vue/singleline-html-element-content-newline: off
  vue/this-in-template: warn
  vue/use-v-on-exact: error
  vue/v-bind-style: warn
  vue/v-on-handler-style: error
  vue/v-on-style: warn
  vue/v-slot-style: warn
  vue/valid-define-options: error
  vue/valid-template-root: error
  vue/valid-v-bind: error
  vue/valid-v-cloak: error
  vue/valid-v-else-if: error
  vue/valid-v-else: error
  vue/valid-v-for: error
  vue/valid-v-html: error
  vue/valid-v-if: error
  vue/valid-v-is: error
  vue/valid-v-model: error
  vue/valid-v-on: error
  vue/valid-v-once: error
  vue/valid-v-pre: error
  vue/valid-v-show: error
  vue/valid-v-slot: error
  vue/valid-v-text: error
